### ISSUE TITLE
High CPU utilization of Executor

### ISSUE THREAD

**Issue by diptanu** [mesos/mesos-go#55] opened 2015-01-15 14:47 UTC
I wrote a custom executor with the new "pure" Go bindings. And I am observing the cpu utilization of the executor process to be always ~100% with load average of the server over or close to 1.00

Can you guys test whether it's the same case with your executors too?

**Comment by diptanu** [comment] 2015-01-15 14:48
@nqn @vladimirvivien ^

**Comment by vladimirvivien** [comment] 2015-01-16 03:48
@diptanu our test executors are simple and don't have benchmarks yet.  Please share more detail about your executor or paste some sample code here.

**Comment by diptanu** [comment] 2015-01-18 00:51
@vladimirvivien I tried to use runtime/pprof to get some samples and see which part of the code is spending more time on cpus. But unfortunately the golang cpu profiler is broken on OSX :(

**Comment by vladimirvivien** [comment] 2015-01-20 10:47
@diptanu Thanks you for pointing this out.  So the issue is on OS X ?  
Also, anything you can pin down that could be the cause is appreciated (executor driver creation, executor driver start/run,  driver http communication, etc).  
Also, what are you doing in your Executor implementation ?  Anything long-running ?

**Comment by diptanu** [comment] 2015-01-25 09:47
@vladimirvivien The issue can be spotted both on OS X and Linux. 

Yeah, I am monitoring processes once I launch them in the executor which is long running. Basically the process is started on a go routine when then starts another go routine to monitor the newly spawned process.

**Comment by vladimirvivien** [comment] 2015-01-30 00:18
@diptanu Do you have any more info about this issue ?  Any info on how to replicate this behavior ?

**Comment by jdef** [comment] 2015-02-20 22:11
@diptanu any updates?

**Comment by diptanu** [comment] 2015-02-26 02:42
@jdef I am not able to test anymore since it's not possible to write an executor with mesos-go without specifying an IP and port where the executor can bind. Mesos Slave doesn't set them, so I am not sure how to write an executor with this library anymore.

**Comment by jdef** [comment] 2015-02-26 04:25
@diptanu some changes were merged recently that allow for an executor driver to optionally be configured with a BindingAddress and BindingPort. They are not required. If they (and HostnameOverride) are not specified, then the hostname should be looked up and an IP address resolved from that.

As a designer of an executor you are now in charge of the command line flags for things like binding address/port, and using them in the DriverConfig (if you want to). You can also query things like the env variable LIBPROCESS_IP (xref https://github.com/mesosphere/kubernetes-mesos/blob/a0a37467a692e60d5c2315a2127605b8a9e15a95/cmd/k8sm-executor/main.go#L72) to determine binding address.

If you've experiencing buggy behavior with the new implementation, please file an issue for it.

xref: https://github.com/mesos/mesos-go/blob/master/executor/executor.go#L39

**Closed** 2015-05-29 10:34 UTC
