### ISSUE TITLE
What is the status of Next Branch

### ISSUE THREAD

**Issue by vladimirvivien** [mesos/mesos-go#240] opened 2016-04-20 15:30 UTC
Hi is the next branch stable, usable, etc ?
Looking to do a talk on new HTTP API, looking for working clients.

Vladimir

**Comment by jdef** [comment] 2016-04-20 21:16
Thanks for asking! The "next" branch is **not** stable. A lot of the
scheduler and executor http v1 API support is there now though. The client
interface is pretty low level. We'll probably implement a higher-level API
at some point (maybe something to make it easier to port frameworks written
against the current API in master).

The Go interfaces are subject to change pending review. So while it's
totally possible to play around with the bits people can expect probably
breakage at some point.

The http v1 specs for scheduler and executor are only beta, and still
experimental as far as Mesos itself is concerned. One of the next bits to
deal with is authentication. And I don't think anyone has tested the SSL
stuff I added. There's still some bugs at the Mesos level w/ respect to the
HTTP API. YMMV.

All that said ... the example scheduler and executor in the cmd/ directory
seem to function as intended.

HTH

**Comment by vladimirvivien** [comment] 2016-04-21 16:23
Awesome @jdef . Yes, that helped.  Thanks.

**Comment by dvonthenen** [comment] 2016-05-23 20:35
@jdef I can see there has been a lot of activity with the next branch since I last took a look at it. I had a couple of questions about this as well.

1. If I chose to implement a framework on the current mesos-go implementation, when the Next branch does get merged to master, in your opinion how much work will it be to adapt my framework to the Next code base? 
2. I am curious as to when you think Next will be ready to go mainstream for use? What is your plan for a date to releasing this?

**Comment by jdef** [comment] 2016-05-23 22:10
A1. It'll likely take some significant work unless there's a shim/compatibility layer added to the next/ API. the API in master defines verbose callback style interfaces and is quite different than the API in next/.  PR's for such a compat layer are welcome!

A2. goal has been to have an initial release of the next/ API sometime this June. Might get pushed to July, but hopefully not much later.

xref #245

**Comment by dvonthenen** [comment] 2016-05-24 14:46
thanks for the info

**Comment by rboyer** [comment] 2016-08-19 14:05
Since Mesos 1.0 is out with the HTTP scheduler/executor API being blessed as stable, what's the timeline for making the mesos-go scheduler/executor client a stable starting point to build frameworks on?

**Comment by jdef** [comment] 2016-08-20 01:01
I'm certainly glad to see interest here! I'd like to do some **minor**
clean up of the mesos-go/next API, and would also like to sync to the
latest mesos v1 protobufs before an initial beta release. It's possible
that an initial release may land in September.

Is lack of a stable Golang-based mesos v1 API blocking your development
efforts?

**Comment by hsawhney09** [comment] 2016-09-01 00:15
Eagerly awaiting the release of the next branch !

**Comment by dhilipkumars** [comment] 2016-09-01 00:19
+1

**Comment by LeoLiuYan** [comment] 2016-09-06 04:00
+1

**Comment by hekaldama** [comment] 2016-10-19 23:07
I am very interested in this and wouldn't mind testing / helping in any way I can.

**Comment by rboyer** [comment] 2016-12-06 19:41
@jdef I have a large (internal) java framework that I'd love to port to Go for non-mesos reasons and the questionable nature of the mesos-go package is the only thing keeping me back. It's a combination of the work not being given any sort of done-ness stamp of approval, and the fact that the ideal branch to build against isn't `master` which is weird.

If you intend to have dual-support for the old and new scheduler/executor apis, would it make sense to move the entire `next` branch to be the `master` branch of a new library like `mesos/mesos-api-go` or something like that?

**Comment by jdef** [comment] 2016-12-06 19:54
great question @rboyer. it's certainly possible to imagine a world in which the old scheduler and executor APIs are supported by a new v1 implementation under the hood. or also to imagine what you suggest: separate projects, one for the old API/impl and one for the new. i can see arguments for both.

my most recent thinking has been to move the older APIs to a `v0/` directory, and the new APIs into a `v1/` directory, keeping both within the `mesos/mesos-go` project. for example, by importing `github.com/mesos/mesos-go/v1` you'd get the `mesos` package for the mesos v1 API. this would facilitate both ongoing maintenance effort in the `v0` tree (mesos still supports v0, after all) as well as new effort in the `v1` tree. and both would be developed on master.

thoughts/concerns/comments?

**Comment by rboyer** [comment] 2016-12-06 22:02
That might work.  Also you might be able to use the http://labix.org/gopkg.in service to keep both variations available with nicer `go get` names.

The one thing to watch out for would be making sure that a transitive library resolution wouldn't download the union of the v0 and v1 dependency chains.

**Comment by shoenig** [comment] 2016-12-07 21:22
Is there an estimate on a blessed v1 branch? Very much looking forward to being able to use this.

**Comment by phylake** [comment] 2017-01-20 22:22
Hi @jdef I was hoping you could post an update on this. I need to write a scheduler for a new project running on Mesos v1 and would like to use Go if possible.

**Comment by jdef** [comment] 2017-02-05 14:39
#274

**Closed by jdef** 2017-02-05 14:39 UTC
Labels: question

**Comment by phylake** [comment] 2017-02-05 16:51
@jdef Thank you!
